baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Nathan Corneloup'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
